//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carros_Full
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carro
    {
        public int id { get; set; }
        public string TipodeCarro { get; set; }
        public int idModelos { get; set; }
        public int idCompañia { get; set; }
        public Nullable<decimal> precio { get; set; }
        public string traccion { get; set; }
        public string transmision { get; set; }
        public string Imagen { get; set; }
        public int Cantidad { get; set; }
        public System.DateTime fechacreada { get; set; }
    
        public virtual Compañia Compañia { get; set; }
        public virtual Modelo Modelo { get; set; }
    }
}
