//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carros_Full
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CarrosEntities : DbContext
    {
        public CarrosEntities()
            : base("name=CarrosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Carro> Carros { get; set; }
        public virtual DbSet<Compañia> Compañia { get; set; }
        public virtual DbSet<Modelo> Modeloes { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
